version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: api/
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3307
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test