version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - web

  api:
    build: api/
    ports:
      - ${API_PORT}:3000
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - web

  back-office:
    build: back-office/
    ports:
      - ${BACK_OFFICE_PORT}:3000
    environment:
      API_HOST: ${API_HOST}
    networks:
      - web

  front-client:
    build: front-client/
    ports:
      - ${FRONT_CLIENT_PORT}:3000
    environment:
      API_HOST: ${API_HOST}
      CHAT_BOT_HOST: ${CHAT_BOT_HOST}
    networks:
      - web


  chat-bot:
    build: chat-bot/
    ports:
      - ${CHAT_BOT_PORT}:5000
    networks:
      - web

  front-bail:
    build: front-bail/
    ports:
      - ${FRONT_BAIL_PORT}:3000
    environment:
      API_HOST: ${API_HOST}
    networks:
      - web

networks:
  web:
    external: true