name: test_action
on: [ push, pull_request ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2

  docker-compose-test:
    runs-on: ubuntu-latest
    name: Docker Compose Action
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.test.yml"
          down-flags: "--volumes"
          services: |
            mysql-db
            api
            back-office
            chat-bot